import { Box, Grid } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import { FeaturedDevHome } from '../components/Home/FeaturedDevHome'
import { Login } from '../components/Home/Login'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hello Next World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.section}>
          <Grid
            display='flex'
          >
            <Box
            marginRight={2.5}
            marginLeft={85}
            >
            
              <Login />
            </Box>
            <Box>
              <FeaturedDevHome />
            </Box>
          </Grid>
        </div>
      </div>
    </>
  )
}

export default Home
